#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace MvcOpenAccess	
{
	public partial class Car
	{
		private int _carId;
		public virtual int CarId 
		{ 
		    get
		    {
		        return this._carId;
		    }
		    set
		    {
		        this._carId = value;
		    }
		}
		
		private string _model;
		public virtual string Model 
		{ 
		    get
		    {
		        return this._model;
		    }
		    set
		    {
		        this._model = value;
		    }
		}
		
		private int? _year;
		public virtual int? Year 
		{ 
		    get
		    {
		        return this._year;
		    }
		    set
		    {
		        this._year = value;
		    }
		}
		
	}
}
